### ISSUE TITLE
Estimation with fe_factory inputs model 

### ISSUE THREAD

**Issue by schenkch** [salvadorgarciamunoz/kipet#59] opened 2018-10-09 21:59 UTC
I created a new branch for the variance and parameter estimation with fe-factory called estim_with_fefactoryinputmodel. I still have an issue though. In the PyomoSimulatorChange I had to include an if clause for checking whether the D_index already exists because the model was already discretized before but in case of pure simulation (for example running Ex_5_sime_fe_by_fe.py) this gives an error because it does not exist. Maybe one of you has an idea of how this could be implemented in a better way?

**Comment by mchlshort** [comment] 2018-10-10 13:59
Hi Christina, could you upload the PyomoSimulatorChange module? I think you may have forgotten to

**Comment by schenkch** [comment] 2018-10-10 14:27
Hi Mike! Yeah, sure. Sorry, I just uploaded it. If anything else is missing, just let me know.

**Comment by mchlshort** [comment] 2018-10-10 19:58
Hi Christina, I think that maybe you have not uploaded all the files. I had a look to see where D_index is first defined and I couldn't find it anywhere. Could you check please? Maybe I just missed it, but I went through every file in kipet/library and only found the if clause you mentioned above, but no sign of the initial declaration. I would assume it was in the TemplateBuilder as it is a part of the pyomo model?

**Comment by schenkch** [comment] 2018-10-10 20:05
That's the one I mean. This if-clause has to be implemented in another way. It is not explicitly implemented anywhere else. It is set with discretisation if the data is already added to the model before. Just uncomment it in the PyomoSimulatorChange and test the parameter estimation example and you will see.
I just had to add zero rows to D for the feeds and round the time index but that does not seem to be the problem. That is in the TemplateBuilderChange. Just look for dfall.

**Comment by mchlshort** [comment] 2018-10-11 15:16
Hi @schenkch, I had a look at the problem and I think there is a pretty simple solution. Just delete the currently set D parameter (set by TemplateBuilder) totally and replace it with the new parameter. This seems to work well. The D_index is automatically generated by pyomo whenever you have more than one index on a var or param (if you have three indices a D_index_0 will also appear). Try replacing the if-clause with these:

"        self.model.del_component(self.model.D)
        self.model.del_component(self.model.D_index)"

Let me know if that fixes the problem for you!

**Comment by mchlshort** [comment] 2018-10-11 15:19
Oh, and I suppose you should include an if-clause to also catch whether D has been created at all for the normal simulation case before trying to replace it.

**Comment by schenkch** [comment] 2018-10-11 15:45
Hi @mchlshort, Thanks. That seems to work. The parameter estimation problem works well although it takes quite a bit of computation time but I can not get the variance estimation to converge. I checked the new model with the inputs and this is created in the right way. If you have an idea regarding another useful option or something that would be great as well.

**Comment by schenkch** [comment] 2018-10-11 23:15
I still found some bugs with the inputs and after I fixed them, the parameter estimation now has similar issues as the variance estimation.

**Comment by schenkch** [comment] 2018-10-19 18:56
I created a new example with inputs. The variance and parameter estimation with fe-factory works now. The example is called Ex_2_estimationfefactoryTempV.py. I have only tested it for spectral data so far. @mchlshort : Can you please test this again and maybe create an example for concentration data as well?

**Comment by mchlshort** [comment] 2018-11-05 19:39
Hi @schenkch, everything seems to work well for the spectroscopic case, however the concentration case is going to require more thought. I have tried to get a concentration example working with inputs this morning, but to no avail. 

The issue is basically that in order to get fe_factory to see the inputs we need to run the sim first with the inputs set. When we are calculating Z at this stage, with concentration inputs C values are also generated, I am assuming as part of the initialization strategy. The problem now is that after running the FESimulator, we now need to add in the C data. When this is done, the existing C-matrix seems to have some issue with data types at the point at which the inputs are used.

I have uploaded an example with a noised C-matrix that you can maybe try and test into the branch 'estim_with_fefactoryinputmodel'. I think that you probably know a bit more about how to interface the 2 data-sets than (the noised C for the concentration estimation and the Z/C obtained from the FESimulator) after working on the fe_factory inputs. The example is 'Ad_5_conc_in_input_conf.py'.

If this explanation didn't make too much sense, please feel free to drop by my desk and I will try to show you.

**Comment by mchlshort** [comment] 2018-11-13 00:03
Christina's new branch is now merged and everything seems to be working really nicely. Will probably discover some bugs once new problems are attempted, but for now this issue is solved.

**Closed as completed by mchlshort** 2018-11-13 00:03 UTC
