### ISSUE TITLE
Issue when installing from new_data branch

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#145] opened 2020-11-08 04:55 UTC
I tried directly cloning "new_data" branch from kwmcbride/kipet repo and ran python setup.py install. I had the following 2 issues:
1. I got the following error when I tried `from kipet import KipetModel`
<img width="647" alt="Screen Shot 2020-11-07 at 11 51 51 PM" src="https://user-images.githubusercontent.com/7705554/98457346-47c51580-2154-11eb-9f36-778ac4c311aa.png">
However, if I run it within the kipet folder, it runs fine.

2. If I use pyomo 5.7.1, I get the following error (works fine with pyomo 5.6.9):
<img width="836" alt="Screen Shot 2020-11-07 at 9 47 33 PM" src="https://user-images.githubusercontent.com/7705554/98457355-6d521f00-2154-11eb-9b43-2b88ad1f73f0.png">

3. This is more a syntax question: If I wanted to explicitly set the linear solver, how can I do that in this new version.

**Comment by kwmcbride** [comment] 2020-11-08 16:02
Thanks for testing the new branch. I am still waiting for the reviews to be done, but you have helped in finding some bugs.

1. The first bug looks like I forgot to put an \_\_init\_\_.py file into the core_methods directory. Could you please try this and see if you fix the error in your install?

2. The second error is simply me not updating the file from my pyomo 5.7 version. The _SetProduct class does not exist anymore and was replaced with SetProduct. I will commit this now.

3. The solver options can be handled in a couple of ways, but this is probably the best way:

Assuming that your ReactionModel is named 'r1':
```
r1.settings.solver.linear_solver = 'ma57'
```

**Comment by notesofdabbler** [comment] 2020-11-08 18:42
I tried reinstalling with latest version of the new_data branch. It removed previous error but gave similar error about not finding post_model_build and top_level. When I copied the blank `__init__.py` to those two folders as you did above, then the install worked fine and the command `from kipet import KipetModel` worked from a different directory also

**Comment by notesofdabbler** [comment] 2020-11-08 20:09
I tried couple of examples after the install (and using pyomo 5.7.1). They are working for the most part. I am listing below a couple of issues I saw:
1. I am getting error when using the command `r1.results.plot()`. The following [notebook](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_examples/Ex1_ode_sim_wk.py.ipynb) has the error. 

2. I am getting an error when using `r1.add_dataset` command since it seems to look in the package directory. When I explicitly specify filename, then it works. The following [notebook](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_examples/Ex7_concentration_input_wk.py.ipynb) has the error.

**Comment by kwmcbride** [comment] 2020-11-09 08:36
Glad to hear that it was simply the issue with \_\_init\_\_.py files.

The new problem is most likely that the directory for charts is not set-up properly. If you add an empty folder "charts" to the kipet directory (same level as library and examples) this should work. I will add this to the current version.

I will look into the add_dataset method, as I am surprised that it does not work and that it works using the full path.

**Comment by kwmcbride** [comment] 2020-11-09 09:03
I have updated the ResultsObject module to handle the missing directory for charts. This should work now.

**Comment by kwmcbride** [comment] 2020-11-12 16:20
I have recreated your error in a Jupyter notebook. The problem is simply that set_directory looks at which file calls the method. When using a Jupyter Notebook, it calls it from the library where the kernel is installed. Since the data is not stored there (it should be in your kipet directory), it will not find your data. This does work from your directory as you have found out. It was written to do this. When you use an absolute path to the data, it works in both instances. This is why it works in the notebook. I am looking into a uniform way to write this now. For now, I would recommend using the absolute file path in the notebook.

**Comment by kwmcbride** [comment] 2020-11-20 16:11
I rewrote the entire way KIPET handles directories and committed the changes to the new_data branch. This adds a new file to the kipet directory "settings.txt" that contains some general settings used in KIPET. I will be expanding this file to handle more of the settings to clean up the differences between KipetModel and ReactionModel settings. For the moment, the most important parts are DATA_DIRECTORY and CHART_DIRECTORY. These handle where the data used in model fittings is stored and where generated charts are saved, respectively. Both directories are automatically set when you install KIPET via new additions in the "setup.py" file. You can override these using the settings object in KipetModel, just make sure it's an absolute path to prevent any strange results.

The new arrangement uses absolute paths at every turn and thus will work from a Jupyter Notebook, in an IDE, or from the command prompt. I have already tested it in each of these.

**Closed as completed** 2020-11-23 13:29 UTC
