### ISSUE TITLE
importing KipetModel gives an error

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#155] opened 2021-01-17 00:12 UTC
I installed the latest version of kipet. I am getting the following error when I import KipetModel:
![image](https://user-images.githubusercontent.com/7705554/104827677-4ee06200-582e-11eb-8efd-166646c6673d.png)
This is the [notebook](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_paresto/jbr_hbv_parmest_logk.ipynb). This was also an example where there was difference in results using `init` vs `initialize` in `add_parameter`. So I wanted to check if I can reproduce it with latest version but ran into the import issue when I did it.

**Comment by kwmcbride** [comment] 2021-01-17 12:24
That is a bug on my part. The clean module does not exist and was used for development. If you comment out that line in the kipet_model.py module, it should work as intended. I will fix this in a pull request.

**Comment by kwmcbride** [comment] 2021-01-17 12:44
This was addressed in #156

**Closed as completed by kwmcbride** 2021-01-17 12:44 UTC
