### ISSUE TITLE
Example 7 using k_aug doesn't seem to be working

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#147] opened 2020-11-24 05:27 UTC
I was trying a variation of [Ex_7_concentration_input.py](https://github.com/salvadorgarciamunoz/kipet/blob/master/kipet/new_examples/Ex_7_concentration_input.py) using k_aug. The notebook is in this [location](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_examples/Ex7_concentration_input_kaug_wk.ipynb). The covariance matrix seems high. 
```
array([[   566.1046434 ,  -3422.01856352],
       [ -3422.01856352, 133117.39905717]])
```

**Comment by kwmcbride** [comment] 2020-11-24 09:44
When using concentration data, you need to provide the component variances yourself. This was inadvertently left out in the update. I will fix this example in the current pull request, but the problem is solved by changing the component addition portion to the following:
```
    # Declare the components and give the initial values
    r1.add_component('A', state='concentration', init=0.001, variance=1e-10)
    r1.add_component('B', state='concentration', init=0.0, variance=1e-11)
    r1.add_component('C', state='concentration', init=0.0, variance=1e-8)

**Comment by kwmcbride** [comment] 2020-11-24 09:47
Since this has been fixed and added to the current pull request, I am closing this.

**Closed as completed by kwmcbride** 2020-11-24 09:47 UTC
Labels: bug
